### PR TITLE
Allow runtime only version of Vue

### PR DESCRIPTION
**Pull request by ferm10n**
Including the vue template compiler in a webpack project increases its size by about 30%. For people who are trying to keep their bundle size low, this can be a problem if they want to use vue-toastr since it requires the template compiler.

In this PR, I have converted the HTML into render functions so the compiler is not needed.

Ideally, it would have been nice to use .vue files, but until this project uses a more up to date version of webpack and vue-loader, that approach was more trouble than it's worth.

Thanks, and enjoy

### CODE REVIEW

**Comment by s4l1h** [comment]
@ferm10n Thanks for contribute 👍 
But can you reverte back **demo.js** and **index.html** ? because demo.js main purpose is readable example documentation. After than it will be merged.
Thanks again.

**Comment by ferm10n** [comment]
Ah I see. My only hesitation is that people might look at the demo and see it using the full version of Vue, and I don't want to make people think they need the compiler build of Vue to use vue-toaster. Especially since vue-toaster didn't specify the template compiler was needed in the first place.

I have two thoughts on this. We could:
- upgrade the project dependencies so we can use proper single file components (.vue files). That would give this project consistency with a lot of other Vue projects I think.
- add a comment where we include Vue, explaining that vue-toaster works without the compiler build, but it's used in the demo because we have a template property. This option would be quicker.

Do you have any suggestions?

**Comment by s4l1h** [comment]
@ferm10n I always prefer **quick** way.
I usually read **example code** when i was **learning** new lang/tools/framework.
We can make **another demo page** which works without template compiler.
After than people can read/copy/paste the code from demo pages.

**Comment by ferm10n** [comment]
@s4l1h alrighty, I removed my changes to the demo and added a note to the HTML demo where the full Vue build is included.

**Pull request merged**
